direction: right

Repository.addTeam -> Store.set
Repository.addDate -> Store.addDate
Repository.addFeelingForDate -> Store.addFeelingForDate
Repository.setTeamByTeamName -> Store.set
Repository.getDateIntervalForTeam -> Store
Repository.getFeelingsForDate -> Store.addFeelingForDate
Repository.getDateForTeam -> Store
Repository.getAllDatesForTeam -> Store
Repository.getTeams
