direction: right

Repository.addTeam -> Store.set
Repository.addDate -> Store.addDate
Repository.addFeelingForDate -> Store
Repository.setTeamByTeamName -> Store.set
Repository.getTeams -> Store
Repository.getDatesForTeam -> Store
Repository.getFeelingsForDate -> Store.addFeelingForDate
Repository.getDateForTeam -> Store
Repository.getAllDatesForTeam -> Store
